# Alignment Error Visualization

This notebook collects COM data from the database and tries to quantify some alignment errors. The main results are shown in the plots at the end of the notebook.

In [1]:
import os
import sys
from pathlib import Path

import numpy as np
import pandas as pd
from collections import OrderedDict
from IPython.display import HTML
from itertools import combinations
from scipy.ndimage import affine_transform
import SimpleITK as sitk


PIPELINE_ROOT = Path('./').absolute().parents[1]
PIPELINE_ROOT = PIPELINE_ROOT.as_posix()
sys.path.append(PIPELINE_ROOT)
print(PIPELINE_ROOT)


/home/eddyod/programming/pipeline/src


In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
from library.controller.sql_controller import SqlController
from library.image_manipulation.filelocation_manager import FileLocationManager
from library.atlas.atlas_utilities import apply_affine_transform, get_affine_transformation, \
fetch_coms, list_coms, compute_affine_transformation
from library.atlas.brain_structure_manager import BrainStructureManager
from library.utilities.utilities_process import M_UM_SCALE, SCALING_FACTOR, random_string, \
read_image, write_image


XGBoost Version: 2.1.4


In [4]:
def sum_square_com(com):
    ss = np.sqrt(sum([s**2 for s in com]))
    return ss

def apply_affine_transformation(volume, matrix):
    """Apply an affine transformation to a 3D volume."""
    transformed_volume = affine_transform(volume, matrix, offset=0, order=1)
    return transformed_volume

In [41]:
moving_name = 'MD589'
fixed_name = 'Allen'
moving_all = fetch_coms(moving_name, scaling_factor=1)
fixed_all = list_coms(fixed_name, scaling_factor=1)
common_keys = list(moving_all.keys() & fixed_all.keys())
moving_src = np.array([moving_all[s] for s in common_keys])
fixed_src = np.array([fixed_all[s] for s in common_keys])
print(len(common_keys))

37


In [42]:
#transformation_matrix = get_affine_transformation(moving_name=moving_name, fixed_name=fixed_name, 
#                                                  scaling_factor=1)
transformation_matrix = compute_affine_transformation(moving_src, fixed_src)
print(transformation_matrix)

[[ 9.96008343e-01  1.69780452e-01  2.72223202e-02 -2.95710421e+03]
 [-8.25783293e-02  1.18030608e+00  1.09038636e-01 -2.89953155e+03]
 [ 1.88559100e-03 -7.08043196e-02  1.09790465e+00  1.21989539e+03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [43]:
# these keys have very high errors: 'RtTg', 'AP'
midbrain_keys = {
            "3N_L",
            "3N_R",
            "4N_L",
            "4N_R",
            "IC",
            "PBG_L",
            "PBG_R",
            "SC",
            "SNC_L",
            "SNC_R",
            "SNR_L",
            "SNR_R",
        }
bad_keys = ('RtTg', 'AP', '3N_L', '3N_R')
bad_keys = ('RtTg', 'AP')
#bad_keys = ('RtTg',)
good_keys = set(common_keys) - set(bad_keys)
print(f'#good_keys={len(good_keys)}')

#good_keys=35


In [44]:
df_list = []
error = []
transformed_dict = {}
for structure in common_keys:
    moving0 = np.array(moving_all[structure])
    fixed0 = np.array(fixed_all[structure]) 
    transformed = apply_affine_transform(moving0, transformation_matrix)
    transformed = [x for x in transformed]
    difference = [a - b for a, b in zip(transformed, fixed0)]
    ss = sum_square_com(difference)
    row = [structure, np.round(moving0), np.round(fixed0), 
           np.round(transformed), np.round(difference), ss]
    df_list.append(row)
    error.append(ss)
    transformed_dict[structure] = transformed
print('RMS', sum(error)/len(df_list))
# MD589 to Allen RMS 260.0211852431133
# MD585 to Allen RMS 263.314352291951
# MD594 to Allen RMS 250.79820210419254
# AtlasV8 disk to Allen RMS 237.0680595008574
# MD585 to MD589 RMS 18.2658167690059

RMS 266.1973052186457


In [46]:
#transformation_matrix = np.hstack([transformation_matrix, t])
#transformation_matrix = np.vstack([transformation_matrix, np.array([0, 0, 0, 1])])
#print(transformation_matrix)
structure = 'SC'
try:
    com = moving_all[structure]
except KeyError:
    structure = common_keys[0]
    com = moving_all[structure]
#com = [10949, 3923, 4399]
print(f'{moving_name} {structure} non trans {np.round(np.array(com))}')
transformed_structure = apply_affine_transform(com, transformation_matrix)
print(f'{moving_name} {structure} apply trans {np.round(transformed_structure/1)}')
print(f'{fixed_name} {structure} {np.round(np.array(fixed_all[structure]))}')
diff = transformed_structure - fixed_all[structure]
print(f'{moving_name}-{fixed_name} {structure} {np.round(diff)}')


MD589 SC non trans [11339.  4729.  4288.]
MD589 SC apply trans [9256. 2214. 5614.]
Allen SC [9140. 2388. 5692.]
MD589-Allen SC [ 115. -174.  -78.]


In [39]:
columns = ['structure', moving_name, fixed_name, 'transformed', 'difference', 'sumsquares']
df = pd.DataFrame(df_list, columns=columns)
df.index.name = 'Index'
df = df.round(4)
df.sort_values(by=['sumsquares'], inplace=True)
#df.to_csv('/home/eddyod/programming/pipeline/docs/sphinx/source/_static/results.csv', index=False)
df.head(50)

structure                   MD585                   Allen  \
Index                                                             
3         VLL_L  [1046.0, 574.0, 283.0]   [946.0, 518.0, 389.0]   
11         5N_R  [1140.0, 549.0, 565.0]  [1019.0, 529.0, 729.0]   
34        LRt_L  [1355.0, 696.0, 288.0]  [1234.0, 699.0, 439.0]   
36         6N_L  [1197.0, 558.0, 381.0]  [1077.0, 521.0, 529.0]   
14        SNR_R   [967.0, 557.0, 582.0]   [844.0, 517.0, 735.0]   
13         6N_R  [1198.0, 557.0, 451.0]  [1077.0, 521.0, 609.0]   
9          3N_L  [1032.0, 457.0, 425.0]   [910.0, 379.0, 552.0]   
1            IC  [1144.0, 312.0, 439.0]  [1040.0, 232.0, 568.0]   
18         4N_L  [1065.0, 458.0, 413.0]   [959.0, 378.0, 543.0]   
0          3N_R  [1023.0, 459.0, 448.0]   [910.0, 379.0, 586.0]   
32        SNC_R   [932.0, 569.0, 560.0]   [836.0, 512.0, 709.0]   
7        Sp5I_R  [1356.0, 574.0, 585.0]  [1211.0, 587.0, 764.0]   
2            SC  [1032.0, 320.0, 454.0]   [914.0, 239.0, 569.0]   
22         5N_L  [1125.0, 559.0, 293.0]  [1019.0, 529.0, 409.0]   
15        LRt_R  [1368.0, 665.0, 521.0]  [1234.0, 699.0, 699.0]   
21        PBG_R  [1057.0, 454.0, 631.0]   [940.0, 385.0, 783.0]   
12        Amb_L  [1293.0, 663.0, 299.0]  [1188.0, 662.0, 432.0]   
29       Sp5I_L  [1352.0, 617.0, 245.0]  [1211.0, 587.0, 375.0]   
6        Sp5O_L  [1255.0, 610.0, 250.0]  [1114.0, 591.0, 379.0]   
33         4N_R  [1059.0, 461.0, 463.0]   [959.0, 377.0, 595.0]   
25         7n_R  [1183.0, 578.0, 532.0]  [1069.0, 548.0, 668.0]   
35         LC_L  [1170.0, 501.0, 341.0]  [1071.0, 428.0, 473.0]   
31         7N_L  [1202.0, 670.0, 319.0]  [1085.0, 678.0, 434.0]   
4          LC_R  [1173.0, 491.0, 511.0]  [1071.0, 428.0, 665.0]   
27       Sp5C_L  [1419.0, 625.0, 263.0]  [1283.0, 590.0, 398.0]   
28        PBG_L  [1061.0, 435.0, 259.0]   [940.0, 384.0, 355.0]   
10         DC_R  [1273.0, 489.0, 635.0]  [1127.0, 500.0, 816.0]   
19        Amb_R  [1301.0, 629.0, 542.0]  [1188.0, 662.0, 706.0]   
20         7n_L  [1167.0, 597.0, 316.0]  [1069.0, 548.0, 471.0]   
26        VLL_R  [1058.0, 583.0, 583.0]   [947.0, 517.0, 750.0]   
24         7N_R  [1225.0, 644.0, 541.0]  [1085.0, 678.0, 705.0]   
23        SNC_L   [943.0, 544.0, 314.0]   [835.0, 512.0, 429.0]   
5         SNR_L   [970.0, 551.0, 310.0]   [844.0, 517.0, 403.0]   
30       Sp5O_R  [1281.0, 574.0, 588.0]  [1114.0, 591.0, 760.0]   
16         DC_L  [1244.0, 523.0, 245.0]  [1127.0, 500.0, 323.0]   
17         RtTg  [1058.0, 619.0, 434.0]   [950.0, 532.0, 569.0]   
8            AP  [1385.0, 566.0, 391.0]  [1265.0, 501.0, 569.0]   

                  transformed            difference  sumsquares  
Index                                                            
3       [940.0, 521.0, 393.0]      [-7.0, 3.0, 4.0]      8.8153  
11     [1018.0, 521.0, 726.0]    [-1.0, -8.0, -3.0]      8.8220  
34     [1229.0, 701.0, 430.0]    [-6.0, 2.0, -10.0]     11.3613  
36     [1078.0, 525.0, 517.0]     [1.0, 3.0, -12.0]     12.1098  
14      [856.0, 514.0, 733.0]    [12.0, -3.0, -2.0]     12.2102  
13     [1076.0, 528.0, 599.0]    [-1.0, 6.0, -10.0]     12.2363  
9       [922.0, 388.0, 550.0]     [11.0, 9.0, -2.0]     14.4258  
1      [1027.0, 226.0, 566.0]   [-13.0, -6.0, -2.0]     14.8451  
18      [953.0, 392.0, 539.0]    [-6.0, 14.0, -4.0]     15.8030  
0       [913.0, 392.0, 576.0]    [2.0, 13.0, -10.0]     16.2694  
32      [823.0, 522.0, 705.0]   [-12.0, 10.0, -4.0]     16.2951  
7      [1220.0, 574.0, 767.0]     [9.0, -13.0, 3.0]     16.3878  
2       [921.0, 225.0, 576.0]     [7.0, -14.0, 7.0]     16.6962  
22     [1013.0, 512.0, 410.0]    [-6.0, -16.0, 1.0]     17.3184  
15     [1233.0, 681.0, 699.0]   [-2.0, -18.0, -1.0]     17.8906  
21      [939.0, 401.0, 790.0]     [-2.0, 17.0, 7.0]     18.3238  
12     [1170.0, 655.0, 435.0]    [-18.0, -7.0, 3.0]     19.6741  
29     [1227.0, 602.0, 374.0]    [16.0, 15.0, -0.0]     21.9122  
6      [1136.0, 584.0, 373.0]    [22.0, -8.0, -6.0]     24.2747  
33    

In [ ]:
com_um = np.array([11339,  4729,  4288.])
origin_allen = np.array([1013, 406, 254])
test_com = np.array([121,  67, 175])
scale = np.array([0.452, 0.452, 20])
origin_neuro = origin_um / scale
volume_shape = np.array([158, 102, 182])
xy_resolution = 0.452
SCALING_FACTOR = 32
scale0 = np.array([xy_resolution*SCALING_FACTOR, xy_resolution*SCALING_FACTOR, 20])
allen_um = np.array([10,10,10])
scale_allen = scale0 / allen_um

In [ ]:
volume_shape = np.array([158, 102, 182])
xy_resolution = 0.452
SCALING_FACTOR = 20
to_um = np.array([0.452*32, 0.452*32, 20])
(volume_shape * to_um) / SCALING_FACTOR