# Alignment Error Visualization

This notebook collects COM data from the database and tries to quantify some alignment errors. The main results are shown in the plots at the end of the notebook.

In [1]:
import os
import sys
from pathlib import Path

import numpy as np
import pandas as pd
from collections import OrderedDict
from IPython.display import HTML
from itertools import combinations
from scipy.ndimage import affine_transform
import SimpleITK as sitk


PIPELINE_ROOT = Path('./').absolute().parents[1]
PIPELINE_ROOT = PIPELINE_ROOT.as_posix()
sys.path.append(PIPELINE_ROOT)
print(PIPELINE_ROOT)


/home/eddyod/programming/pipeline/src


In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
from library.controller.sql_controller import SqlController
from library.image_manipulation.filelocation_manager import FileLocationManager
from library.atlas.atlas_utilities import apply_affine_transform, get_affine_transformation, \
fetch_coms, list_coms, compute_affine_transformation
from library.atlas.brain_structure_manager import BrainStructureManager
from library.utilities.utilities_process import M_UM_SCALE, SCALING_FACTOR, random_string, \
read_image, write_image


In [4]:
def sum_square_com(com):
    ss = np.sqrt(sum([s**2 for s in com]))
    return ss

def apply_affine_transformation(volume, matrix):
    """Apply an affine transformation to a 3D volume."""
    transformed_volume = affine_transform(volume, matrix, offset=0, order=1)
    return transformed_volume

In [5]:
moving_name = 'DK55'
fixed_name = 'AtlasV8'
moving_all = list_coms(moving_name, scaling_factor=1)
fixed_all = fetch_coms(fixed_name, scaling_factor=1)
common_keys = list(moving_all.keys() & fixed_all.keys())
bad_keys = ('RtTg', 'AP')
#bad_keys = ('RtTg',)
bad_keys = ()
good_keys = set(common_keys) - set(bad_keys)

moving_src = np.array([moving_all[s] for s in good_keys])
fixed_src = np.array([fixed_all[s] for s in good_keys])
print(len(common_keys))

29


In [6]:
moving_all

{'7N_L': [13080.7, 7323.6, 3660.0],
 '7N_R': [12927.3, 7183.8, 6300.0],
 'Tz_R': [12015.9, 7570.06, 5480.0],
 'Tz_L': [12009.4, 7635.5, 4460.0],
 '5N_R': [12198.9, 6011.09, 6320.0],
 'Pn_L': [10897.3, 7409.56, 4280.0],
 'Pn_R': [11083.8, 7421.77, 5580.0],
 '3N_L': [11207.5, 5005.76, 4620.0],
 '3N_R': [11172.8, 4960.67, 4900.0],
 '6N_R': [12691.9, 6174.66, 5240.0],
 '6N_L': [12747.7, 6215.66, 4500.0],
 '10N_R': [14330.9, 5936.56, 5240.0],
 'Amb_R': [13785.2, 6869.11, 6340.0],
 'Amb_L': [13717.5, 7135.54, 3660.0],
 'DC_L': [13327.7, 5646.89, 2660.0],
 'DC_R': [13334.3, 5283.99, 7080.0],
 'LC_R': [12679.9, 5218.19, 5680.0],
 'LC_L': [12584.0, 5309.77, 3960.0],
 'LRt_L': [14545.3, 7358.92, 3680.0],
 'LRt_R': [14848.1, 7225.04, 6280.0],
 '5N_L': [12184.6, 6245.08, 3400.0],
 'PBG_R': [11309.0, 4916.5, 6740.0],
 'PBG_L': [11314.1, 5133.68, 2860.0],
 'AP': [14439.6, 5705.57, 4920.0],
 '4N_L': [11525.2, 5043.96, 4460.0],
 '4N_R': [11474.0, 4986.83, 4940.0],
 '10N_L': [14451.13, 6652.42, 5820.0]

In [7]:
#transformation_matrix = get_affine_transformation(moving_name=moving_name, fixed_name=fixed_name, 
#                                                  scaling_factor=1)
transformation_matrix = compute_affine_transformation(moving_src, fixed_src)
print(transformation_matrix)

[[ 1.00161836e+00 -3.60715444e-03 -1.09577172e-02 -1.12492477e+02]
 [ 7.95601847e-02  7.99077250e-01 -1.18628904e-02  4.38934248e+02]
 [-1.06040005e-01 -2.72150865e-02  9.07737472e-01  1.47314659e+03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [8]:
df_list = []
error = []
transformed_dict = {}
for structure in common_keys:
    moving0 = np.array(moving_all[structure])
    fixed0 = np.array(fixed_all[structure]) 
    transformed = apply_affine_transform(moving0, transformation_matrix)
    transformed = [x for x in transformed]
    difference = [a - b for a, b in zip(transformed, fixed0)]
    ss = sum_square_com(difference)
    row = [structure, np.round(moving0), np.round(fixed0), 
           np.round(transformed), np.round(difference), ss]
    df_list.append(row)
    error.append(ss)
    transformed_dict[structure] = transformed
print('RMS', sum(error)/len(df_list))
# MD589 to Allen RMS 260.0211852431133
# MD585 to Allen RMS 263.314352291951
# MD594 to Allen RMS 250.79820210419254
# AtlasV8 disk to Allen RMS 237.0680595008574
# MD585 to MD589 RMS 18.2658167690059

RMS 190.01406664601984


In [9]:
#transformation_matrix = np.hstack([transformation_matrix, t])
#transformation_matrix = np.vstack([transformation_matrix, np.array([0, 0, 0, 1])])
#print(transformation_matrix)
structure = 'SC'
try:
    com = moving_all[structure]
except KeyError:
    structure = common_keys[0]
    com = moving_all[structure]
#com = [1095, 392, 519]
print(f'{moving_name} {structure} non trans {np.round(np.array(com))}')
transformed_structure = apply_affine_transform(com, transformation_matrix)
print(f'{moving_name} {structure} apply trans {np.round(transformed_structure/1)}')
print(f'{fixed_name} {structure} {np.round(np.array(fixed_all[structure]))}')
diff = transformed_structure - fixed_all[structure]
print(f'{moving_name}->{fixed_name} {structure} {np.round(diff)}')


DK55 SC non trans [11190.  3080.  4640.]
DK55 SC apply trans [11034.  3735.  4415.]
AtlasV8 SC [10949.  3924.  4399.]
DK55->AtlasV8 SC [  85. -188.   16.]


In [10]:
columns = ['structure', moving_name, fixed_name, 'transformed', 'difference', 'sumsquares']
df = pd.DataFrame(df_list, columns=columns)
df.index.name = 'Index'
df = df.round(4)
df.sort_values(by=['sumsquares'], inplace=True)
#df.to_csv('/home/eddyod/programming/pipeline/docs/sphinx/source/_static/results.csv', index=False)
df.head(50)

structure                       DK55                    AtlasV8  \
Index                                                                   
26         3N_L  [11208.0, 5006.0, 4620.0]  [11014.0, 5264.0, 4317.0]   
23         Tz_L  [12009.0, 7636.0, 4460.0]  [11831.0, 7413.0, 4009.0]   
4          Tz_R  [12016.0, 7570.0, 5480.0]  [11818.0, 7395.0, 5017.0]   
25         5N_L  [12185.0, 6245.0, 3400.0]  [12014.0, 6306.0, 3088.0]   
6          3N_R  [11173.0, 4961.0, 4900.0]  [10985.0, 5279.0, 4575.0]   
17         4N_L  [11525.0, 5044.0, 4460.0]  [11365.0, 5279.0, 4179.0]   
10         4N_R  [11474.0, 4987.0, 4940.0]  [11337.0, 5280.0, 4674.0]   
21         5N_R  [12199.0, 6011.0, 6320.0]  [11980.0, 6184.0, 5809.0]   
5          6N_L  [12748.0, 6216.0, 4500.0]  [12584.0, 6276.0, 4057.0]   
12         Pn_R  [11084.0, 7422.0, 5580.0]  [10843.0, 7236.0, 5106.0]   
2          6N_R  [12692.0, 6175.0, 5240.0]  [12588.0, 6270.0, 4765.0]   
28        Amb_L  [13718.0, 7136.0, 3660.0]  [13616.0, 7187.0, 3231.0]   
1          LC_L  [12584.0, 5310.0, 3960.0]  [12336.0, 5683.0, 3569.0]   
22         7N_R  [12927.0, 7184.0, 6300.0]  [12834.0, 7191.0, 5649.0]   
27        Amb_R  [13785.0, 6869.0, 6340.0]  [13608.0, 6972.0, 5699.0]   
14         Pn_L  [10897.0, 7410.0, 4280.0]  [10858.0, 7244.0, 3964.0]   
7          DC_L  [13328.0, 5647.0, 2660.0]  [13125.0, 5847.0, 2403.0]   
8         PBG_R  [11309.0, 4916.0, 6740.0]  [11244.0, 5053.0, 6299.0]   
9            AP  [14440.0, 5706.0, 4920.0]  [14394.0, 6217.0, 4318.0]   
11         7N_L  [13081.0, 7324.0, 3660.0]  [12792.0, 7329.0, 3362.0]   
15           SC  [11190.0, 3080.0, 4640.0]  [10949.0, 3924.0, 4399.0]   
0          DC_R  [13334.0, 5284.0, 7080.0]  [13106.0, 5547.0, 6529.0]   
24         LC_R  [12680.0, 5218.0, 5680.0]  [12310.0, 5608.0, 5239.0]   
13        LRt_L  [14545.0, 7359.0, 3680.0]  [14380.0, 7519.0, 3300.0]   
19        10N_R  [14331.0, 5937.0, 5240.0]  [14443.0, 6437.0, 4618.0]   
3         PBG_L  [11314.0, 5134.0, 2860.0]  [11308.0, 5098.0, 2594.0]   
16        LRt_R  [14848.0, 7225.0, 6280.0]  [14324.0, 7269.0, 5549.0]   
18         7n_L  [12651.0, 6182.0, 4020.0]  [12387.0, 6657.0, 3368.0]   
20        10N_L  [14451.0, 6652.0, 5820.0]  [14491.0, 6493.0, 4087.0]   

                     transformed               difference  sumsquares  
Index                                                                  
26     [11044.0, 5276.0, 4342.0]       [30.0, 12.0, 25.0]     41.1264  
23     [11840.0, 7443.0, 4040.0]        [9.0, 30.0, 31.0]     44.0398  
4      [11835.0, 7379.0, 4967.0]     [17.0, -16.0, -50.0]     54.9590  
25     [12032.0, 6358.0, 3097.0]        [18.0, 52.0, 9.0]     55.9804  
6      [11007.0, 5234.0, 4601.0]      [22.0, -45.0, 27.0]     56.6016  
17     [11364.0, 5333.0, 4162.0]      [-0.0, 55.0, -16.0]     57.2045  
10     [11308.0, 5278.0, 4605.0]     [-29.0, -2.0, -69.0]     74.8904  
21     [12015.0, 6138.0, 5753.0]     [35.0, -47.0, -56.0]     80.8483  
5      [12584.0, 6367.0, 4037.0]      [-0.0, 91.0, -20.0]     92.6573  
12     [10901.0, 7185.0, 5161.0]      [59.0, -51.0, 55.0]     94.8341  
2      [12520.0, 6321.0, 4716.0]     [-68.0, 50.0, -49.0]     97.5794  
28     [13561.0, 7189.0, 3147.0]      [-54.0, 2.0, -85.0]    100.6989  
1      [12429.0, 5636.0, 3589.0]      [93.0, -47.0, 20.0]    106.3533  
22     [12741.0, 7133.0, 5626.0]    [-93.0, -58.0, -24.0]    112.4862  
27     [13601.0, 6949.0, 5579.0]    [-8.0, -23.0, -119.0]    121.6877  
14     [10729.0, 7176.0, 4001.0]    [-129.0, -68.0, 37.0]    150.5979  
7      [13187.0, 5980.0, 2321.0]     [63.0, 133.0, -82.0]    168.6278  
8      [11123.0, 5187.0, 6258.0]   [-121.0, 135.0, -41.0]    185.2170  
9      [14276.0, 6089.0, 4253.0]  [-118.0, -128.0, -65.0]    185.9828  
11     [12923.0, 7288.0, 3209.0]   [131.0, -40.0, -153.0]    204.9616  
15     [11034.0, 3735.0, 4415.0]     [85.0, -188.0, 16.0]    207.2872  
0      [13147.0, 5638.0, 6342.0]     [40.0, 91.0, -187.0]    211.5867  
24     [12507.